#!/usr/bin/env node
// Regenerates src/assets/apple-touch-icon.ts from src/assets/apple-touch-icon.png.
// Run by hand whenever the icon changes: node scripts/generate-icon.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const png = readFileSync(new URL('../src/assets/apple-touch-icon.png', import.meta.url));
const base64 = png.toString('base64');

const output = `// Generated by scripts/generate-icon.mjs from src/assets/apple-touch-icon.png — do not edit by hand.
export const APPLE_TOUCH_ICON_HREF = \`data:image/png;base64,${base64}\`;
`;

writeFileSync(new URL('../src/assets/apple-touch-icon.ts', import.meta.url), output);
console.log('wrote src/assets/apple-touch-icon.ts');
